packages:
  - apps/*
  - packages/*
  - cli

catalog:
  '@types/fs-extra': ^11.0.4
  '@types/jsonwebtoken': ^9.0.10
  '@types/ramda': ^0.31.1
  axios: ^1.13.2
  dayjs: ^1.11.19
  fs-extra: ^11.3.2
  jsonwebtoken: ^9.0.2
  mysql2: ^3.15.3
  ramda: ^0.32.0
  zod: ^4.1.12

catalogs:
  bundler:
    '@vitejs/plugin-basic-ssl': ^2.1.0
    '@vitejs/plugin-react': ^5.1.1
    vite: ^7.2.4
    tsup: ^8.5.1
  cli:
    cac: ^6.7.14
    commander: ^14.0.2
    picocolors: ^1.1.1
  linter:
    '@eslint-react/eslint-plugin': ^2.3.5
    '@eslint/js': ^9.39.1
    '@types/node': ^24.10.1
    eslint: ^9.39.1
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    globals: ^16.5.0
    prettier: ^3.6.2
    typescript: ^5.9.3
    typescript-eslint: ^8.47.0
  react:
    '@ant-design/icons': ^6.1.0
    '@types/react': ^19.2.6
    '@types/react-dom': ^19.2.3
    ahooks: ^3.9.6
    antd: 5.29.0
    react: ^19.2.0
    react-dom: ^19.2.0
    react-error-boundary: ^6.0.0
    react-router: ^7.9.6
    react-router-dom: ^7.9.6
    zustand: ^5.0.8
  server:
    '@koa/bodyparser': ^6.0.0
    '@koa/router': ^14.0.0
    '@types/koa': ^3.0.1
    '@types/koa-compose': ^3.2.9
    '@types/koa-logger': ^3.1.5
    '@types/koa__router': ^12.0.5
    '@types/statuses': ^2.0.6
    '@types/ws': ^8.18.1
    koa: ^3.1.1
    koa-compose: 4.1.0
    koa-jwt: ^4.0.4
    koa-logger: ^4.0.0
    koa-unless: ^1.0.7
    statuses: ^2.0.2
    ws: ^8.18.3
  tools:
    nodemon: ^3.1.11
    tsx: ^4.20.6
