packages:
  - apps/*
  - packages/*
  - cli

catalog:
  '@types/fs-extra': ^11.0.4
  axios: 1.13.2
  fs-extra: ^11.3.2

catalogs:
  bundler:
    '@vitejs/plugin-react': ^5.1.1
    tsup: ^8.5.0
    vite: ^7.2.2
  bunlder:
    tsup: ^8.5.1
  cli:
    commander: ^14.0.2
    picocolors: ^1.1.1
  linter:
    '@eslint-react/eslint-plugin': ^2.3.5
    '@eslint/js': ^9.39.1
    '@types/node': ^24.10.1
    eslint: ^9.39.1
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    globals: ^16.5.0
    prettier: ^3.6.2
    typescript: ^5.9.3
    typescript-eslint: ^8.47.0
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    antd: ^5.29.0
    react: ^19.2.0
    react-dom: ^19.2.0
  server:
    '@koa/router': ^14.0.0
    '@types/koa': ^3.0.1
    '@types/koa__router': ^12.0.5
    koa: ^3.1.1
    koa-router: ^14.0.0
  tools:
    nodemon: ^3.1.11
    tsx: ^4.20.6
